apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express
        image: express-k8s-demo:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: express-svc
spec:
  type: ClusterIP
  selector:
    app: express
  ports:
  - port: 3000
    targetPort: 3000
