version: '3.8'

services:
  web:
    image: nginx:1.27
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf.ro
    depends_on:
      - api:
          condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 10s
      timeout: 30s
      retries: 5

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 10s
      timeout: 3s